name: Heroku Deployment CI  # Specifies the name of the workflow

on:  # Defines events that trigger the workflow
  push:  # Triggers the workflow when code is pushed
    branches:  # Specifies which branches to watch
      - main  # Run workflow on push to the 'main' branch
  pull_request:  # Triggers the workflow on pull requests
    branches:  # Specifies which branches to watch
      - main  # Run workflow on pull request to the 'main' branch

jobs:  # Defines the jobs that will be executed in this workflow
  build:  # Defines a job named 'build'
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu environment

    steps:  # List of steps to execute in the 'build' job
      - name: Checkout repository  # Step to checkout the repository
        uses: actions/checkout@v3  # Uses the checkout action to clone the repository

      - name: Set up Node.js  # Step to set up the Node.js environment
        uses: actions/setup-node@v3  # Uses the setup-node action to configure Node.js
        with:
          node-version: '18'  # Specifies Node.js version 18 to use

      - name: Install dependencies  # Step to install project dependencies
        run: npm install  # Runs 'npm install' to install required Node.js packages

      - name: Run tests  # Step to run the test suite
        run: npm test  # Runs 'npm test' to execute the automated tests
        
      - name: Install Heroku CLI  # Install the Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate to Heroku  # Authenticate using Heroku API key
        run: |
          echo ${{ secrets.HEROKU_OAUTH_TOKEN }} | heroku auth:token

      - name: Add Heroku remote  # Add Heroku app remote for git deployment
        run: git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy to Heroku  # Deploy to Heroku by pushing to the Heroku git remote
        run: git push heroku main  # Push the code to Heroku's main branch
        