name: Heroku Deployment CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Check if Heroku API Key is available
        run: echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" | head -c 10  # print part of the key for verification

      - name: Clear Heroku Auth
        run: heroku auth:logout || true  # Clear any existing session

      - name: Authenticate to Heroku
        run: |
          echo "Authenticating with Heroku..."
          echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
          heroku whoami

      - name: List Heroku Apps
        run: heroku apps  # Check if your Heroku app is visible

      - name: Add Heroku remote
        run: git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy to Heroku
        run: git push heroku main
